stages:
  - test
#  - build

tests:
  stage: test
  image: rust
  script:
    - cd fraug
    - cargo test

#build:amd64:
#  stage: build
#  image: rust
#  script:
#    - cargo build --release
#  artifacts:
#    paths:
#      - target/release/rust-gitlab-example
