- name: Repeat
  rp_kwargs: {times: 10}
  tsaug_class: null
  tsaug_kwargs: null

- name: Scaling
  rp_kwargs: {min: 1.5, max: 2.0}
  tsaug_class: null
  tsaug_kwargs: {min: 1.5, max: 2.0}

- name: Rotation
  rp_kwargs: {anchor: 1.0}
  tsaug_class: null
  tsaug_kwargs: null

- name: Jittering
  rp_kwargs: {standard_deviation: 0.1}
  tsaug_class: AddNoise
  tsaug_kwargs: {scale: 0.1}

- name: Drop
  rp_kwargs: {percentage: 0.1, default: 0.0}
  tsaug_class: Dropout
  tsaug_kwargs: {p: 0.1, fill: 0.0}

- name: Crop
  rp_kwargs: {size: 64}
  tsaug_class: Crop
  tsaug_kwargs: {size: 64}

- name: AmplitudePhasePerturbation
  rp_kwargs: {magnitude_std: -10.0, phase_std: 1.7, is_time_domain: true}
  tsaug_class: null
  tsaug_kwargs: null

- name: FrequencyMask
  rp_kwargs: {mask_width: 10, is_time_domain: true}
  tsaug_class: null
  tsaug_kwargs: null

- name: Quantize
  rp_kwargs: {levels: 10}
  tsaug_class: Quantize
  tsaug_kwargs: {n_levels: 10}

- name: Resize
  rp_kwargs: {size: 200}
  tsaug_class: Resize
  tsaug_kwargs: {size: 200}

- name: Reverse
  rp_kwargs: {}
  tsaug_class: Reverse
  tsaug_kwargs: {}

- name: Permutate
  rp_kwargs: {window_size: 20, segment_size: 5}
  tsaug_class: null
  tsaug_kwargs: {n_segments: 50}

- name: AddNoise
  rp_kwargs: {noise_type: Slope, mean: 0.0, std_dev: 0.1, bounds: [0.01, 0.02]}
  tsaug_class: AddNoise
  tsaug_kwargs: {scale: 0.1}

- name: RandomTimeWarpAugmenter
  rp_kwargs: {window_size: 50, speed_ratio_range: [0.5, 10.0]}
  tsaug_class: null
  tsaug_kwargs: null

- name: Pool
  rp_kwargs: {kind: Average, size: 10}
  tsaug_class: Pool
  tsaug_kwargs: {kind: ave, size: 10}

- name: Drift
  rp_kwargs: {max_drift: 1.0, n_drift_points: 5}
  tsaug_class: Drift
  tsaug_kwargs: {max_drift: 1.0, n_drift_points: 5}

- name: Convolve
  rp_kwargs: {window: Gaussian, size: 31}
  tsaug_class: Convolve
  tsaug_kwargs:
    window: ['gaussian', 2.0]
    size: 31