[package]
name = "rats"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
rand = "0.9.1"
rand_distr = "0.5.1"
rayon = "1.10.0"
rustfft = "6"
rustdct = "0.7"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
cargo-tarpaulin = "0.27"